KREW_INSTALL_TYPE="github_release"
KREW_GITHUB_REPO="kubernetes-sigs/krew"
KREW_ARCHIVE_TYPE="tar.gz"
KREW_ASSET_PATTERN="krew-\${DETECT_OS}_\${DETECT_ARCH}.tar.gz"
KREW_BIN_PATH="krew-\${DETECT_OS}_\${DETECT_ARCH}"
