KUBECOLOR_INSTALL_TYPE="github_release"
KUBECOLOR_GITHUB_REPO="kubecolor/kubecolor"
KUBECOLOR_ARCHIVE_TYPE="tar.gz"
KUBECOLOR_ASSET_PATTERN="kubecolor_\${VERSION}_\${DETECT_OS}_\${DETECT_ARCH}.tar.gz"
