VAULT_INSTALL_TYPE="github_release"
VAULT_GITHUB_REPO="hashicorp/vault"
VAULT_ARCHIVE_TYPE="zip"
VAULT_ASSET_PATTERN="vault_\${VERSION}_\${DETECT_OS}_\${DETECT_ARCH}.zip"
VAULT_DOWNLOAD_URL="https://releases.hashicorp.com/vault/\${VERSION}/vault_\${VERSION}_\${DETECT_OS}_\${DETECT_ARCH}.zip"
